[theme]
base = "light"
primaryColor = "#0072B2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#222222"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
maxUploadSize = 50
